[font]
size = 10.5
offset = { x = 0, y = 0 } 

[font.normal]
#family = "JetBrainsMono NF"
family = "BlexMono Nerd Font Medium"
style = "Regular"

[window]
opacity = 0.7
padding = { x = 8, y = 8 }
dynamic_padding = true

[general]
#import = ["./themes/themes/vesper.toml"]
import = ["./themes/cynosure_dark.toml"]
#import = ["/home/aos/.config/alacritty/themes/themes/nord.toml"]
